/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UniButton {
        "type": string;
    }
    interface UniCard {
        "header": string;
    }
    interface UniDivider {
    }
    interface UniPager {
        "defaultPage": string;
        "layout": string;
    }
    interface UniTag {
        "size": string;
        "theme": string;
        "type": string;
    }
}
export interface UniPagerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUniPagerElement;
}
declare global {
    interface HTMLUniButtonElement extends Components.UniButton, HTMLStencilElement {
    }
    var HTMLUniButtonElement: {
        prototype: HTMLUniButtonElement;
        new (): HTMLUniButtonElement;
    };
    interface HTMLUniCardElement extends Components.UniCard, HTMLStencilElement {
    }
    var HTMLUniCardElement: {
        prototype: HTMLUniCardElement;
        new (): HTMLUniCardElement;
    };
    interface HTMLUniDividerElement extends Components.UniDivider, HTMLStencilElement {
    }
    var HTMLUniDividerElement: {
        prototype: HTMLUniDividerElement;
        new (): HTMLUniDividerElement;
    };
    interface HTMLUniPagerElement extends Components.UniPager, HTMLStencilElement {
    }
    var HTMLUniPagerElement: {
        prototype: HTMLUniPagerElement;
        new (): HTMLUniPagerElement;
    };
    interface HTMLUniTagElement extends Components.UniTag, HTMLStencilElement {
    }
    var HTMLUniTagElement: {
        prototype: HTMLUniTagElement;
        new (): HTMLUniTagElement;
    };
    interface HTMLElementTagNameMap {
        "uni-button": HTMLUniButtonElement;
        "uni-card": HTMLUniCardElement;
        "uni-divider": HTMLUniDividerElement;
        "uni-pager": HTMLUniPagerElement;
        "uni-tag": HTMLUniTagElement;
    }
}
declare namespace LocalJSX {
    interface UniButton {
        "type"?: string;
    }
    interface UniCard {
        "header"?: string;
    }
    interface UniDivider {
    }
    interface UniPager {
        "defaultPage"?: string;
        "layout"?: string;
        "onPageChange"?: (event: UniPagerCustomEvent<string>) => void;
    }
    interface UniTag {
        "size"?: string;
        "theme"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "uni-button": UniButton;
        "uni-card": UniCard;
        "uni-divider": UniDivider;
        "uni-pager": UniPager;
        "uni-tag": UniTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uni-button": LocalJSX.UniButton & JSXBase.HTMLAttributes<HTMLUniButtonElement>;
            "uni-card": LocalJSX.UniCard & JSXBase.HTMLAttributes<HTMLUniCardElement>;
            "uni-divider": LocalJSX.UniDivider & JSXBase.HTMLAttributes<HTMLUniDividerElement>;
            "uni-pager": LocalJSX.UniPager & JSXBase.HTMLAttributes<HTMLUniPagerElement>;
            "uni-tag": LocalJSX.UniTag & JSXBase.HTMLAttributes<HTMLUniTagElement>;
        }
    }
}
